### ISSUE TITLE
Rutas del microfront afectan al front padre

### ISSUE THREAD

**Issue by MotherJammer** [Experiencia-de-usuario-2023/mf-panel#1]
El microfront redirige a espacios del front-padre que no le corresponden (en vez de actualizarse el mismo componente) sin afectar al resto. El fragmento conflictivo de código está en app.js y es el siguiente:

![image](https://github.com/Experiencia-de-usuario-2023/mf-panel/assets/56158772/d4f872e2-6c61-4364-a387-ef76eadb6c9a)

Al especificar rutas de la página, causa que la recarga de todo d-meetflow en vez de avanzar hacia la siguiente fase dentro del ciclo de vida de la reunión. Hay que implementar una dinámica **dentro del componente** para que solo afecte su flujo personal y no la navegación completa de la página

**Comment by Danaxar** [comment]
Lo solucioné agregando botones de "etapa anterior" y "etapa siguiente", sin embargo. Aún no logro editar el ciclo de vida, que da para una nueva issue
